---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: development
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        name: myapp
        image: nginx
        ports:
          - containerPort: 80:80
        cpu: 100m
        memory: 128Mi
      automountServiceAccountToken: false