version: '3'

services:
    pydevops:
        build:
            context: .
            dockerfile: python.dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        container_name: pydevops
        networks:
            stddocker-app-network:
                ipv4_address: 11.0.0.8

networks:
    stddocker-app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "11.0.0.0/16"