name: test python code example

on:
  push:
    branches: [ devops ]

jobs:
  test-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7' 
      - run: python firstTest.py
